// <auto-generated />
namespace GoaGaraget.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedmember : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmember));
        
        string IMigrationMetadata.Id
        {
            get { return "201802191005222_added member"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
