using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GoaGaraget.Models
{
    public class Garage
    {
        public int Id { get; set; }
        public String Name { get; set; }
        public int Price { get; set; }
        public int Size { get; set; }
        [ForeignKey("GarageId")]
        public virtual ICollection<ParkingSpace> ParkingSpaces { get; set; }

        //public int CurrentMcParkingSpotId { get; set; }
        //public ParkingSpace CurrentMcParkingSpot { get; set; }
        public Garage()
        {
            this.Name = "autogenerated Price 30 Size 10";
            this.Price = 30;
            this.Size = 10;
            this.ParkingSpaces = new List<ParkingSpace>();
        }

        public Garage(string name, int size, int price)
        {
            this.Name = name;
            this.Price = price;
            this.Size = size;
            this.ParkingSpaces = new List<ParkingSpace>();

        }
    }
}